# Generated by Django 2.2.3 on 2020-03-01 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fnp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArticleExemple',
        ),
    ]
