# Generated by Django 2.2.10 on 2020-03-09 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fnp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalizedArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('predicted_label', models.IntegerField()),
                ('fake_p', models.FloatField()),
                ('dodgy_p', models.FloatField()),
                ('real_p', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('body_text', models.TextField()),
                ('label', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WordDictionary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='ArticleExemple',
        ),
    ]
