# Generated by Django 2.2.10 on 2020-03-02 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fnp', '0003_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='DictionaryEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_id', models.TextField()),
                ('url', models.TextField()),
                ('formatted', models.TextField()),
                ('q_class', models.IntegerField()),
            ],
        ),
    ]
