# Generated by Django 2.2.10 on 2020-03-02 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fnp', '0004_dictionaryentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordDictionary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.TextField()),
            ],
        ),
    ]
